language: go

apt:
  packages:
    - libasound2-dev

go:
  - "1.10"
  - "tip"

notifications:
  on_success: false
  on_failure: always

install: go get -t zikichombo.org/sio/...

script: go test zikichombo.org/sio/...





