language: go

apt:
  packages:
    - libasound2-dev
go:
  - "1.10"
  - "tip"

notifications:
  on_success: false
  on_failure: always

install: sudo apt-get install libasound2-dev && go get -t -x zikichombo.org/sio/...

script: go test -x zikichombo.org/sio/...





