language: go

apt:
  packages:
    - libasound2-dev
    - gcc-4.9

go:
  - "1.10"
  - "tip"

notifications:
  on_success: false
  on_failure: always

install: sudo apt-get install libasound2-dev && sudo apt-get install gcc-4.9 && CFLAGS="std=gnu11" go get -t zikichombo.org/sio/...

env: CFLAGS="std=gnu11"
script: go test zikichombo.org/sio/...





